/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package ejava;

import org.junit.jupiter.api.Test;
import org.junit.jupiter.params.ParameterizedTest;
import org.junit.jupiter.params.provider.CsvSource;

import static org.junit.jupiter.api.Assertions.*;

import java.util.List;

class AppTest {

    @Test
    public void testMonthLenght() {
        final List<String> MONTHS = Utilities.getMonth();

        assertEquals(12, MONTHS.size());
        assertEquals("Agosto", MONTHS.get(7));
    }

    @ParameterizedTest
    @CsvSource({
            "47884005, Y", "44740803, F", "87922261, T", "96414547, L", "33332163, B", "67131703, Q", "32893545, A",
            "11060631, T", "60811296, D", "81513467, H"
    })
    public void testDniNumber(int number, String letter) {
        assertEquals(Utilities.getDniLetterByRest(number), letter);
    }

    @Test
    public void testThrowable(){
        assertThrows(ArrayIndexOutOfBoundsException.class, Utilities::throwError);
    }

}
