/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package t1;

import main.java.t1.Undo;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {
        Undo undo = Undo.getInstance();
        undo.addCommand("command1");
        undo.addCommand("command2");
        System.out.println(undo.getHistory()); // Imprime [command1, command2]
        undo.undoCommand();
        System.out.println(undo.getHistory()); // Imprime [command1]
    }
    }

