/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package test;

import java.util.ArrayList;
import java.util.List;

import handler.Item;

public class App {
    public String getGreeting() {
        return "Hello World!";
    }

    public static void main(String[] args) {

        public static List<Item> get


        System.out.println(new App().getGreeting());
        // Crear NPCs, Items, Ciudades
        // Consultar items, vendedores, etc.
        // Simular compra y venta
        // Serializar información a JSON
        /*
        ObjectMapper objectMapper = new ObjectMapper();
        String json = objectMapper.writeValueAsString(npc);
        */
    }
}
